{{ if .Values.loki.enabled -}}
# Temporal workaround until https://github.com/grafana/helm-charts/pull/159 is merged
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-loki-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: ws-manager
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: bitnami/kubectl:1.20.0
        command:
          - /bin/bash
          - -c
          - |
            DATA=$(kubectl get secret loki-gitpod -o jsonpath='{.data.loki\.yaml}')
            kubectl patch secret loki --patch="{\"stringDdata\": {\"loki.yaml\": \"$DATA\"}}"
{{ end }}
