{{ if .Values.loki.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: loki-gitpod
  labels:
    app: loki
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  loki.yaml: |-
    # https://grafana.com/docs/loki/latest/configuration/
    # enable multi-tenancy
    auth_enabled: true

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 10m
      chunk_retain_period: 5m
      chunk_encoding: snappy
      max_chunk_age: 10m
      chunk_target_size: 1572864

    schema_config:
      configs:
        - from: 2020-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        bucketnames: {{ .Values.loki.bucketName }}
        endpoint: minio:9000
        access_key_id: {{ .Values.minio.accessKey }}
        secret_access_key: {{ .Values.minio.secretKey }}
        insecure: true
        s3forcepathstyle: true

      boltdb_shipper:
        shared_store: s3
        active_index_directory: /data/loki/index
        cache_location: /data/loki/boltdb-cache

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
{{ end }}
